package com.arrietty.dao;

import com.arrietty.entity.OtherTag;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


@Mapper
public interface OtherTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_tag
     *
     * @mbg.generated
     */
    int insert(OtherTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_tag
     *
     * @mbg.generated
     */
    OtherTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_tag
     *
     * @mbg.generated
     */
    List<OtherTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OtherTag record);

    OtherTag selectByName(String name);
}