package com.arrietty.dao;

import com.arrietty.entity.Profile;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long profileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    int insert(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    Profile selectByPrimaryKey(Long profileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    List<Profile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Profile record);

    Profile queryByUserId(Long userId);
}