package com.arrietty.dao;

import com.arrietty.entity.TextbookTag;
import java.util.List;

public interface TextbookTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    int insert(TextbookTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    TextbookTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    List<TextbookTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextbookTag record);
}