server:
  port: 8000
  ssl:
    enable: true
    key-store: classpath:ssl/server-one.p12
    key-store-password: robert
    key-store-type: PKCS12
    key-alias: server-one
    trust-store: classpath:ssl/trustKeys.p12
    trust-store-password: robert
    trust-store-type: PKCS12

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/arrietty_fat_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    hostname: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 5000

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.arrietty.entity



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
  file: log/info.log
  level:
    com:
      arrietty:
        info

auth:
  token-obtain-url: https://localhost:8001/app/rest/keycloak/auth?clientId=%s&authType=%s
  access-token-obtain-url: https://localhost:8001/app/rest/keycloak/token?token=%s
  user-info-obtain-url: https://localhost:8001/app/rest/keycloak/welcome
  client-id: test

file:
  base-image-directory: C:/Users/yz391/Pictures/arrietty
  max-avatar-image-size: 1048576
