package com.arrietty.entity;

import java.io.Serializable;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_id
     *
     * @mbg.generated
     */
    private Long imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.external_image_id
     *
     * @mbg.generated
     */
    private String externalImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.upload_user_id
     *
     * @mbg.generated
     */
    private Long uploadUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_type
     *
     * @mbg.generated
     */
    private String imageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_format
     *
     * @mbg.generated
     */
    private String imageFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_id
     *
     * @return the value of image.image_id
     *
     * @mbg.generated
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_id
     *
     * @param imageId the value for image.image_id
     *
     * @mbg.generated
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.external_image_id
     *
     * @return the value of image.external_image_id
     *
     * @mbg.generated
     */
    public String getExternalImageId() {
        return externalImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.external_image_id
     *
     * @param externalImageId the value for image.external_image_id
     *
     * @mbg.generated
     */
    public void setExternalImageId(String externalImageId) {
        this.externalImageId = externalImageId == null ? null : externalImageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.upload_user_id
     *
     * @return the value of image.upload_user_id
     *
     * @mbg.generated
     */
    public Long getUploadUserId() {
        return uploadUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.upload_user_id
     *
     * @param uploadUserId the value for image.upload_user_id
     *
     * @mbg.generated
     */
    public void setUploadUserId(Long uploadUserId) {
        this.uploadUserId = uploadUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_type
     *
     * @return the value of image.image_type
     *
     * @mbg.generated
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_type
     *
     * @param imageType the value for image.image_type
     *
     * @mbg.generated
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_format
     *
     * @return the value of image.image_format
     *
     * @mbg.generated
     */
    public String getImageFormat() {
        return imageFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_format
     *
     * @param imageFormat the value for image.image_format
     *
     * @mbg.generated
     */
    public void setImageFormat(String imageFormat) {
        this.imageFormat = imageFormat == null ? null : imageFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", imageId=").append(imageId);
        sb.append(", externalImageId=").append(externalImageId);
        sb.append(", uploadUserId=").append(uploadUserId);
        sb.append(", imageType=").append(imageType);
        sb.append(", imageFormat=").append(imageFormat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}