package com.arrietty.entity;

import java.io.Serializable;
import java.util.Date;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.owner_email
     *
     * @mbg.generated
     */
    private String ownerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_format
     *
     * @mbg.generated
     */
    private String imageFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.dateAdded
     *
     * @mbg.generated
     */
    private Date dateadded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.content
     *
     * @mbg.generated
     */
    private byte[] content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.owner_email
     *
     * @return the value of image.owner_email
     *
     * @mbg.generated
     */
    public String getOwnerEmail() {
        return ownerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.owner_email
     *
     * @param ownerEmail the value for image.owner_email
     *
     * @mbg.generated
     */
    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail == null ? null : ownerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_format
     *
     * @return the value of image.image_format
     *
     * @mbg.generated
     */
    public String getImageFormat() {
        return imageFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_format
     *
     * @param imageFormat the value for image.image_format
     *
     * @mbg.generated
     */
    public void setImageFormat(String imageFormat) {
        this.imageFormat = imageFormat == null ? null : imageFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.type
     *
     * @return the value of image.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.type
     *
     * @param type the value for image.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.dateAdded
     *
     * @return the value of image.dateAdded
     *
     * @mbg.generated
     */
    public Date getDateadded() {
        return dateadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.dateAdded
     *
     * @param dateadded the value for image.dateAdded
     *
     * @mbg.generated
     */
    public void setDateadded(Date dateadded) {
        this.dateadded = dateadded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.content
     *
     * @return the value of image.content
     *
     * @mbg.generated
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.content
     *
     * @param content the value for image.content
     *
     * @mbg.generated
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ownerEmail=").append(ownerEmail);
        sb.append(", imageFormat=").append(imageFormat);
        sb.append(", type=").append(type);
        sb.append(", dateadded=").append(dateadded);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}