package com.arrietty.entity;

import java.io.Serializable;
import java.util.Date;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_type
     *
     * @mbg.generated
     */
    private String imageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_size
     *
     * @mbg.generated
     */
    private Integer imageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.upload_time
     *
     * @mbg.generated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.user_id
     *
     * @return the value of image.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.user_id
     *
     * @param userId the value for image.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_type
     *
     * @return the value of image.image_type
     *
     * @mbg.generated
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_type
     *
     * @param imageType the value for image.image_type
     *
     * @mbg.generated
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_size
     *
     * @return the value of image.image_size
     *
     * @mbg.generated
     */
    public Integer getImageSize() {
        return imageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_size
     *
     * @param imageSize the value for image.image_size
     *
     * @mbg.generated
     */
    public void setImageSize(Integer imageSize) {
        this.imageSize = imageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.upload_time
     *
     * @return the value of image.upload_time
     *
     * @mbg.generated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.upload_time
     *
     * @param uploadTime the value for image.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", imageType=").append(imageType);
        sb.append(", imageSize=").append(imageSize);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}