package com.arrietty.entity;

import java.io.Serializable;

public class Profile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.profile_id
     *
     * @mbg.generated
     */
    private Long profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.school_year
     *
     * @mbg.generated
     */
    private Integer schoolYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.avatar_image_id
     *
     * @mbg.generated
     */
    private Long avatarImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.class_year
     *
     * @mbg.generated
     */
    private Integer classYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.bio
     *
     * @mbg.generated
     */
    private String bio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profile
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.profile_id
     *
     * @return the value of profile.profile_id
     *
     * @mbg.generated
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.profile_id
     *
     * @param profileId the value for profile.profile_id
     *
     * @mbg.generated
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.school_year
     *
     * @return the value of profile.school_year
     *
     * @mbg.generated
     */
    public Integer getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.school_year
     *
     * @param schoolYear the value for profile.school_year
     *
     * @mbg.generated
     */
    public void setSchoolYear(Integer schoolYear) {
        this.schoolYear = schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.major
     *
     * @return the value of profile.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.major
     *
     * @param major the value for profile.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.user_id
     *
     * @return the value of profile.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.user_id
     *
     * @param userId the value for profile.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.avatar_image_id
     *
     * @return the value of profile.avatar_image_id
     *
     * @mbg.generated
     */
    public Long getAvatarImageId() {
        return avatarImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.avatar_image_id
     *
     * @param avatarImageId the value for profile.avatar_image_id
     *
     * @mbg.generated
     */
    public void setAvatarImageId(Long avatarImageId) {
        this.avatarImageId = avatarImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.class_year
     *
     * @return the value of profile.class_year
     *
     * @mbg.generated
     */
    public Integer getClassYear() {
        return classYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.class_year
     *
     * @param classYear the value for profile.class_year
     *
     * @mbg.generated
     */
    public void setClassYear(Integer classYear) {
        this.classYear = classYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.bio
     *
     * @return the value of profile.bio
     *
     * @mbg.generated
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.bio
     *
     * @param bio the value for profile.bio
     *
     * @mbg.generated
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", profileId=").append(profileId);
        sb.append(", schoolYear=").append(schoolYear);
        sb.append(", major=").append(major);
        sb.append(", userId=").append(userId);
        sb.append(", avatarImageId=").append(avatarImageId);
        sb.append(", classYear=").append(classYear);
        sb.append(", bio=").append(bio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}