package com.arrietty.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class TextbookTag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.isbn
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.publisher
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.edition
     *
     * @mbg.generated
     */
    private String edition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.original_price
     *
     * @mbg.generated
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook_tag.course_id
     *
     * @mbg.generated
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.id
     *
     * @return the value of textbook_tag.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.id
     *
     * @param id the value for textbook_tag.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.title
     *
     * @return the value of textbook_tag.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.title
     *
     * @param title the value for textbook_tag.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.isbn
     *
     * @return the value of textbook_tag.isbn
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.isbn
     *
     * @param isbn the value for textbook_tag.isbn
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.author
     *
     * @return the value of textbook_tag.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.author
     *
     * @param author the value for textbook_tag.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.publisher
     *
     * @return the value of textbook_tag.publisher
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.publisher
     *
     * @param publisher the value for textbook_tag.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.edition
     *
     * @return the value of textbook_tag.edition
     *
     * @mbg.generated
     */
    public String getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.edition
     *
     * @param edition the value for textbook_tag.edition
     *
     * @mbg.generated
     */
    public void setEdition(String edition) {
        this.edition = edition == null ? null : edition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.original_price
     *
     * @return the value of textbook_tag.original_price
     *
     * @mbg.generated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.original_price
     *
     * @param originalPrice the value for textbook_tag.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column textbook_tag.course_id
     *
     * @return the value of textbook_tag.course_id
     *
     * @mbg.generated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column textbook_tag.course_id
     *
     * @param courseId the value for textbook_tag.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textbook_tag
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", isbn=").append(isbn);
        sb.append(", author=").append(author);
        sb.append(", publisher=").append(publisher);
        sb.append(", edition=").append(edition);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", courseId=").append(courseId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}